# Generated by Django 6.0.3 on 2026-03-25 16:37

import django.core.validators
import django.db.models.deletion
import user.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='The contact number can have + sign in the beginning and max 15 digits without delimiters', regex='^\\+?[1-9][0-9]{7,14}$')])),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Multi factor authentication enabled')),
                ('social_only', models.BooleanField(default=False, help_text='For login with social auth.')),
                ('is_staff', models.BooleanField(default=False)),
                ('password_changed_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at', 'first_name'),
                'permissions': (('view_user_analytics', 'Can view user analytics'),),
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_info', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser or device', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Session expiration time', null=True)),
                ('token_jti', models.CharField(blank=True, help_text='JTI of refresh token for this session', max_length=255, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ('-last_activity',),
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_userse_user_id_a71b04_idx'), models.Index(fields=['session_key'], name='user_userse_session_aa43d0_idx'), models.Index(fields=['expires_at'], name='user_userse_expires_9b7f40_idx')],
            },
        ),
    ]
