# Generated by Django 6.0.3 on 2026-04-18 16:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
