# Generated by Django 6.0.3 on 2026-04-19 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='invite_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymember',
            name='invite_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='companymember',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
